reverseproxy:
  # host: "" # default listen on all interfaces
  # port: 8000 # default
  session:
    # header: X-Session-Id # default
    # timeout: 300 # default 5 minutes
    salt: CHANGE_ME
    
mgmt:
  # host: "" # default listen on all interfaces
  # port: 8080 # default port for the management interface
  key: CHANGE_ME # Key used to authenticate to management apis

docker:
  # host: unix:///var/run/docker.sock # default unix socket
  
  # Configuration for the docker reverse proxy
  container-name: ctf-reverse-proxy # default container name
  
  # Docker compose configuration
  # compose:
    # workdir: . # Default workdir where the docker compose file is stored
    # file: docker-compose.yml # Default docker compose file name