version: "3"
services:
  reverseproxy:
    container_name: ctf-reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile
    image: ctf-reverseproxy
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./docker-compose-ctf.yml:/docker-compose-ctf.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
